// game/src/components/Nav.vue
<script lang="ts">
import { defineComponent } from "vue";
import { removeAuthToken } from "shared/auth";
import { FRONTOFFICE_ENDPOINT } from "shared/endpoints";

import { routes } from "../router";
import { useAuth } from "../auth";

export default defineComponent({
  data() {
    const auth = useAuth();
    return {
      auth,
      routes: routes.filter(
        (route) =>
          !/Register|Login|NotFound|Index/.test(route.name || "")
      ),
      opened: false,
    };
  },
  computed: {
    userProfile() {
      return FRONTOFFICE_ENDPOINT + "users/" + this.auth.uuid;
    },
  },
  methods: {
    async logout() {
      removeAuthToken();
      await this.auth.try();
    },
  },
});
</script>

<template>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <router-link class="navbar-item" to="/">
        <img alt="Animal House Logo" src="/logo.png" class="mr-4" />
        Animal House Game
      </router-link>

      <a
        role="button"
        class="navbar-burger"
        v-bind:class="{ 'is-active': opened }"
        v-on:click="opened = !opened"
        aria-label="menu"
        aria-expanded="false"
        data-target="nav"
      >
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="nav" class="navbar-menu" v-bind:class="{ 'is-active': opened }">
      <div class="navbar-start">
        <!-- TODO: are these links accessible? not working with <space> -->
        <router-link
          v-for="route in routes"
          v-bind:to="route.path"
          class="navbar-item"
          >{{ route.name }}</router-link
        >
      </div>

      <div class="navbar-end">
        <div v-if="auth.authenticated" class="navbar-item">
          <a class="mr-4 has-text-white" :href="userProfile">{{
            auth.username
          }}</a>
          <button @click="logout" class="button is-light">Log out</button>
        </div>
        <div v-else class="navbar-item">
          <div class="buttons">
            <!-- TODO: are these links accessible? not working with <space> -->
            <router-link to="/register" class="button is-primary">
              <strong>Sign up</strong>
            </router-link>
            <router-link to="/login" class="button is-light"
              >Log in</router-link
            >
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>

// frontoffice/src/components/nav.tsx
import * as React from "react";
import { Link } from "react-router-dom";
import { removeAuthToken } from "shared/auth";

import { useAuth } from "../auth";
import { pages } from "../pages/index";

const Nav: React.FC = () => {
  const [opened, setOpened] = React.useState(false);
  const [auth, setAuth] = useAuth();
  const logout = React.useCallback(() => {
    removeAuthToken();
    setAuth(false);
  }, [removeAuthToken, setAuth]);
  return (
    <nav
      className="navbar is-primary"
      role="navigation"
      aria-label="main navigation"
    >
      <div className="navbar-brand">
        <Link className="navbar-item" to="/">
          <img alt="Animal House Logo" src="/logo.png" className="mr-4" />
          Animal House Frontoffice
        </Link>

        <a
          role="button"
          className={`navbar-burger ${opened ? "is-active" : ""}`}
          onClick={() => setOpened(!opened)}
          aria-label="menu"
          aria-expanded="false"
          data-target="nav"
        >
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="nav" className={`navbar-menu ${opened ? "is-active" : ""}`}>
        <div className="navbar-start">
          {pages.map((page, i) => (
            <Link key={i} to={page.url} className="navbar-item">
              {page.name}
            </Link>
          ))}
        </div>

        <div className="navbar-end">
          {auth.authenticated ? (
            <div className="navbar-item">
              <Link
                className="mr-4 has-text-white"
                to={`/users/${auth.user._id}`}
              >
                {auth.user.username}
              </Link>
              <button onClick={logout} className="button is-light">
                Log out
              </button>
            </div>
          ) : (
            <div className="navbar-item">
              <div className="buttons">
                <Link to="/register" className="button is-primary">
                  <strong>Sign up</strong>
                </Link>
                <Link to="/login" className="button is-light">
                  Log in
                </Link>
              </div>
            </div>
          )}
        </div>
      </div>
    </nav>
  );
};

export default Nav;
