// frontoffice/src/components/app.tsx
import * as React from "react";
import { isAuthenticated } from "shared/auth";

import { useAuth } from "../auth";
import Nav from "./nav";

const App: React.FC<React.PropsWithChildren<{}>> = ({ children }) => {
  const [auth, setAuth] = useAuth();
  React.useEffect(() => {
    if (auth.user == null && isAuthenticated()) setAuth(true);
  }, []);

  return (
    <>
      <Nav />
      <main style={{ flex: 1 }} className="m-5">
        <React.Suspense fallback={<h1>loading...</h1>}>
          {children}
        </React.Suspense>
      </main>
    </>
  );
};

export default App;

// game/src/App.vue
<script lang="ts">
import { defineComponent } from "vue";
import Nav from "./Nav.vue";

import { useAuth } from "./auth";

export default defineComponent({
  async setup() {
    await useAuth().try();
  },
  components: {
    Nav,
  },
});
</script>

<template>
  <Nav />
  <main style="flex: 1" class="m-5">
    <Suspense>
      <router-view />
      <template #fallback> Loading... </template>
    </Suspense>
  </main>
</template>
