// game/src/pages/Index.vue
<template>
  <div class="container">
    <aside class="menu">
      <p class="menu-label">Services</p>
      <ul class="menu-list">
        <li><router-link to="/trivia">Trivia</router-link></li>
        <li><router-link to="/videos">Videos</router-link></li>
        <li><router-link to="/help">Help</router-link></li>
      </ul>
      <p class="menu-label">Games</p>
      <ul class="menu-list">
        <li><router-link to="/leaderboard/quiz">Leaderboards</router-link></li>
        <li><router-link to="/quiz">Quiz</router-link></li>
        <li><router-link to="/memory">Memory</router-link></li>
        <li><router-link to="/hangman">Hangman</router-link></li>
        <li><router-link to="/spot">Spot</router-link></li>
      </ul>
    </aside>
  </div>
</template>

// frontoffice/src/pages/index.tsx
import * as React from "react";
import { Link } from "react-router-dom";

export const pages = ["Store", "Services", "Boards", "Leaderboard"];

const Index: React.FC = () => {
  const links = pages.map((page: string) =>
    <li><Link to={page.toLowerCase()}>{page}</Link></li>);
  return (<div className="container">
    <aside className="menu">
      <p className="menu-label">Index</p>
      <ul className="menu-list">
        {links}
      </ul>
    </aside>
  </div>);
};

export default Index;
